// Draws the hero banner's text in the Fizz pixel font, as vector shapes, into the banner SVGs.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: Apache-2.0 OR MIT

// Usage: bun scripts/build-hero.ts [--check]
//   --check  fail if the committed SVGs differ from what this would write (used by validate)
//
// The text is drawn from the glyph grids, so the banner needs no font to display: it looks the same
// as an image on the landing page, in the README on GitHub and anywhere else an SVG is shown.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FACES, faceEntries, type Entry } from '../packages/engine/src/font/build';
import { traceOutline } from '../packages/engine/src/font/outline';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FILES = ['assets/hero.svg', 'site/assets/hero.svg'];
const START = '<!-- hero-text:start (generated by scripts/build-hero.ts) -->';
const END = '<!-- hero-text:end -->';

const glyphs = (file: string): Map<number, Entry> => {
  const spec = FACES.find((f) => f.file === file);
  if (!spec) throw new Error(`no face ${file}`);
  return new Map(faceEntries(spec).map((e) => [e.cp, e]));
};
const bold = glyphs('fizz-bold');
const regular = glyphs('fizz-regular');
const mono = glyphs('fizz-mono-regular');

/** One run of text: its characters, colour and face. */
interface Run {
  text: string;
  fill: string;
  face?: Map<number, Entry>;
}

/** The width of runs laid end to end, in glyph pixels. */
function widthOf(runs: Run[], face: Map<number, Entry>): number {
  let w = 0;
  for (const r of runs) for (const ch of r.text) w += advance(r.face ?? face, ch);
  return w;
}

function advance(face: Map<number, Entry>, ch: string): number {
  const e = face.get(ch.codePointAt(0) as number);
  if (!e) throw new Error(`Fizz has no glyph for ${JSON.stringify(ch)}`);
  return e.placed.adv;
}

/** Path data for runs of text with the top-left of the first cell at (x, y), `s` pixels per glyph pixel. */
function drawRuns(
  runs: Run[],
  face: Map<number, Entry>,
  x: number,
  y: number,
  s: number,
): string[] {
  const out: string[] = [];
  let pen = 0;
  for (const r of runs) {
    const f = r.face ?? face;
    let d = '';
    for (const ch of r.text) {
      const e = f.get(ch.codePointAt(0) as number);
      if (!e) throw new Error(`Fizz has no glyph for ${JSON.stringify(ch)}`);
      for (const c of traceOutline(e.placed.rows, 9, pen + e.placed.ox)) {
        d += c.map((p, i) => `${i ? 'L' : 'M'}${x + p.x * s} ${y + (9 - p.y) * s}`).join('') + 'Z';
      }
      pen += e.placed.adv;
    }
    if (d) out.push(`<path fill="${r.fill}" d="${d}"/>`);
  }
  return out;
}

/** Text with optional pixel shadows: each layer is the same text moved down by `dy` pixels. */
function text(
  runs: Run[],
  face: Map<number, Entry>,
  x: number,
  y: number,
  s: number,
  shadows: { fill: string; dy: number }[] = [],
): string {
  const layers: string[] = [];
  for (const sh of [...shadows].reverse()) {
    layers.push(
      ...drawRuns(
        runs.map((r) => ({ ...r, fill: sh.fill })),
        face,
        x,
        y + sh.dy * s,
        s,
      ),
    );
  }
  layers.push(...drawRuns(runs, face, x, y, s));
  return layers.join('');
}

const run = (t: string, fill: string, face?: Map<number, Entry>): Run => ({
  text: t,
  fill,
  ...(face ? { face } : {}),
});

function generate(): string {
  const parts: string[] = [];
  const BLACK = '#000000';
  const ROSE = '#f43f5e';
  // Eyebrow, title, subtitle and tagline, left-aligned at the same x as the art's text column.
  parts.push(`<g aria-hidden="true">`);
  parts.push(text([run('Ben Blaze in', '#ffaa40')], bold, 82, 70, 2, [{ fill: BLACK, dy: 1 }]));
  const title = [run('Lieutenant Fizz', '#ffffff')];
  const titleScale = widthOf(title, bold) * 6 <= 700 ? 6 : 5;
  parts.push(
    text(title, bold, 80, 102, titleScale, [
      { fill: ROSE, dy: 1 },
      { fill: BLACK, dy: 2 },
    ]),
  );
  parts.push(text([run('Episode 1 · The Cocoa Caper', '#b4bfce')], regular, 83, 196, 2));
  parts.push(
    text(
      [run('A Keen-style platformer on the Liminal Retro Engine', '#7c8796')],
      regular,
      83,
      228,
      2,
    ),
  );
  // Tech badge: its frame is hand-drawn, sized here to the text.
  const badge = [
    run('rust', '#ffaa40'),
    run(' → ', '#5a6273'),
    run('wasm', '#a78bfa'),
    run(' + ', '#5a6273'),
    run('three.js', '#22d3ee'),
    run(' + ', '#5a6273'),
    run('undertone', '#2ec66a'),
  ];
  const bw = widthOf(badge, mono) * 2 + 32;
  const bx = 1166 - bw;
  parts.push(
    `<rect x="${bx}" y="30" width="${bw}" height="38" rx="10" fill="#0f0c09" fill-opacity="0.85" stroke="#333847" stroke-width="1"/>`,
  );
  parts.push(text(badge, mono, bx + 16, 38, 2));
  // Bottom info line.
  const info = [
    run('pogo', '#9aa4b2'),
    run(' | ', '#333847'),
    run('fizz', '#9aa4b2'),
    run(' | ', '#333847'),
    run('stomp', '#9aa4b2'),
    run(' | ', '#333847'),
    run('gumdrop doors', '#9aa4b2'),
    run(' · ', '#333847'),
    run('Liminal HQ', '#7c8796'),
  ];
  parts.push(text(info, regular, 80, 272, 2));
  parts.push('</g>');
  return parts.join('\n  ');
}

const check = process.argv.includes('--check');
const block = `${START}\n  ${generate()}\n  ${END}`;
let stale = false;
for (const file of FILES) {
  const path = join(root, file);
  const src = readFileSync(path, 'utf8');
  const a = src.indexOf(START);
  const b = src.indexOf(END);
  if (a < 0 || b < 0) throw new Error(`${file} has no hero-text markers`);
  const next = src.slice(0, a) + block + src.slice(b + END.length);
  if (next === src) continue;
  if (check) stale = true;
  else writeFileSync(path, next);
}
if (check && stale) {
  console.error('The hero banner SVGs are out of date. Run: bun run build:hero');
  process.exit(1);
}
console.log(check ? 'Hero banner is up to date.' : 'Hero banner text written.');
